In [1]:
import polars as pl
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import polars as pl

inicial = (
    pl.scan_parquet(r"C:\Users\Usuario\OneDrive\Documentos\Covid_AC.parquet")
    .select([
        "paciente_idade",
        "paciente_dataNascimento",
        "paciente_enumSexoBiologico",
        "paciente_endereco_nmMunicipio",
        "paciente_endereco_uf",
        "vacina_dataAplicacao",
        "vacina_fabricante_nome",
        "vacina_nome"
    ])
    .with_columns(
        pl.col("paciente_idade").cast(pl.Int64, strict=False),
        pl.col("paciente_dataNascimento").str.to_date("%Y-%m-%d", strict=False),
        pl.col("vacina_dataAplicacao").str.to_date("%Y-%m-%d", strict=False)
    )
)

display(inicial.head(5).collect())

shape: (5, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ paciente_i ┆ paciente_d ┆ paciente_e ┆ paciente_ ┆ paciente_ ┆ vacina_da ┆ vacina_fa ┆ vacina_no │
│ dade       ┆ ataNascime ┆ numSexoBio ┆ endereco_ ┆ endereco_ ┆ taAplicac ┆ bricante_ ┆ me        │
│ ---        ┆ nto        ┆ logico     ┆ nmMunicip ┆ uf        ┆ ao        ┆ nome      ┆ ---       │
│ i64        ┆ ---        ┆ ---        ┆ io        ┆ ---       ┆ ---       ┆ ---       ┆ str       │
│            ┆ date       ┆ str        ┆ ---       ┆ str       ┆ date      ┆ str       ┆           │
│            ┆            ┆            ┆ str       ┆           ┆           ┆           ┆           │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 30         ┆ 1992-06-29 ┆ F          ┆ RIO       ┆ AC        ┆ 2023-03-0 ┆ PFIZER    ┆ COVID-19  │
│            ┆            ┆            ┆ BRANCO    ┆           ┆ 3         ┆           ┆ PFIZER -  │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ COMIRNATY │
│ 45         ┆ 1976-03-30 ┆ F          ┆ RIO       ┆ AC        ┆ 2021-06-1 ┆ ASTRAZENE ┆ COVID-19  │
│            ┆            ┆            ┆ BRANCO    ┆           ┆ 7         ┆ CA/FIOCRU ┆ ASTRAZENE │
│            ┆            ┆            ┆           ┆           ┆           ┆ Z         ┆ CA/FIOCRU │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ Z -…      │
│ 14         ┆ 2007-02-02 ┆ M          ┆ RODRIGUES ┆ AC        ┆ 2021-12-0 ┆ PFIZER    ┆ COVID-19  │
│            ┆            ┆            ┆ ALVES     ┆           ┆ 1         ┆           ┆ PFIZER -  │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ COMIRNATY │
│ 71         ┆ 1950-06-04 ┆ M          ┆ BELEM     ┆ PA        ┆ 2021-11-2 ┆ PFIZER    ┆ COVID-19  │
│            ┆            ┆            ┆           ┆           ┆ 5         ┆           ┆ PFIZER -  │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ COMIRNATY │
│ 32         ┆ 1990-04-05 ┆ M          ┆ RIO       ┆ AC        ┆ 2022-07-2 ┆ ASTRAZENE ┆ COVID-19  │
│            ┆            ┆            ┆ BRANCO    ┆           ┆ 0         ┆ CA/FIOCRU ┆ ASTRAZENE │
│            ┆            ┆            ┆           ┆           ┆           ┆ Z         ┆ CA/FIOCRU │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ Z -…      │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

In [3]:
"""Métricas: Média, Mediana, Moda, Variância, Desvio Padrão, Amplitude"""

# Construindo a expressão de cálculo
metricas1 = inicial.select([
    pl.col("paciente_idade").mean().alias("Média"),
    pl.col("paciente_idade").median().alias("Mediana"),

    # Moda retorna uma lista, pegamos o primeiro valor
    pl.col("paciente_idade").mode().first().alias("Moda"),

    pl.col("paciente_idade").var().alias("Variância"),

    pl.col("paciente_idade").std().alias("Desvio_Padrão"),

    (
        pl.col("paciente_idade").max() -
        pl.col("paciente_idade").min()
    ).alias("Amplitude_Total")

]).collect()

print("\n--- Estatísticas Descritivas (Idade dos Pacientes) ---")

display(metricas1)

--- Estatísticas Descritivas (Idade dos Pacientes) ---

shape: (1, 6)
┌───────────┬─────────┬──────┬────────────┬───────────────┬─────────────────┐
│ Média     ┆ Mediana ┆ Moda ┆ Variância  ┆ Desvio_Padrão ┆ Amplitude_Total │
│ ---       ┆ ---     ┆ ---  ┆ ---        ┆ ---           ┆ ---             │
│ f64       ┆ f64     ┆ i64  ┆ f64        ┆ f64           ┆ i64             │
╞═══════════╪═════════╪══════╪════════════╪═══════════════╪═════════════════╡
│ 35.725003 ┆ 34.0    ┆ 18   ┆ 389.816883 ┆ 19.743781     ┆ 125             │
└───────────┴─────────┴──────┴────────────┴───────────────┴─────────────────┘